### PR TITLE
Ignore '@' in path when parsing urls

### PR DESCRIPTION
**Pull request by idanga**

### CODE REVIEW

**Comment by idanga** [comment]
Sorry about the failing test, fixing it now.

**Comment by rucek** [comment]
Hi @renatoathaydes and @idanga! I came here because of a similar issue with the `@` in path. Let me elaborate a bit on why this is needed. The problem is with requests like:
```
POST /api/users/test@example.com HTTP/1.1
```
which, when using the `allowIllegalStartLineCharacters()` option, causes a
```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -16
	at java.lang.String.substring(String.java:1967)
	at rawhttp.core.HttpMetadataParser.parseUriLenient(HttpMetadataParser.java:463)
	at rawhttp.core.HttpMetadataParser.parseUri(HttpMetadataParser.java:420)
	at rawhttp.core.HttpMetadataParser.buildRequestLine(HttpMetadataParser.java:160)
	at rawhttp.core.HttpMetadataParser.parseRequestLine(HttpMetadataParser.java:77)
	at rawhttp.core.RawHttp.parseRequest(RawHttp.java:133)
	at rawhttp.core.RawHttp.parseRequest(RawHttp.java:119)
	at rawhttp.core.RawHttp.parseRequest(RawHttp.java:89)
```
which is caused by the fact that we're effectively calling `substring(16, 0)`.

When `allowIllegalStartLineCharacters()` is not set, i.e. when the `new URI()` constructor is used, it works correctly. 

To reproduce, you can add the following test case to https://github.com/renatoathaydes/rawhttp/blob/master/rawhttp-core/src/test/kotlin/rawhttp/core/RequestLineTest.kt#L53:
```kotlin
row("POST /api/users/test@example.com HTTP/1.1", HttpVersion.HTTP_1_1, "POST", "/api/users/test@example.com", "POST /api/users/test@example.com HTTP/1.1")
```

I'm really looking forward to this being merged and released. I'll be happy to help if you need anything more.

**Comment by renatoathaydes** [comment]
@rucek thanks for explaining the problem. I will merge this and release asap. Thanks also to @idanga .

**Comment by idanga** [comment]
Thanks for following up on this! (and apologies for the ghosting...)

**Comment by renatoathaydes** [comment]
I've released this now! `rawhttp-core` version `2.2.1`.

**Comment by rucek** [comment]
@renatoathaydes thanks for your instant reaction!

**Pull request merged**
