### PR TITLE
Correctly handle uri encoded query string and "mixed" content

### PR DESCRIPTION
**Pull request by idanga**
This change enables parsing of (legal) query strings with encoded "&".
It also allows such query strings to be parsed correctly with "allowIllegalCharacters".

### CODE REVIEW

**Comment by renatoathaydes** [comment]
Hi @idanga thanks for your PR. Could you please create a issue first, so that I know exactly what the problem is you're addressing here?

**Comment by idanga** [comment]
Created issue - #15 
(Also adding some UTs)

**Comment by idanga** [comment]
@renatoathaydes Ready to merge. Added UT to show it does not break with illegal encoding and also making sure that multiple-byte percent-encoded pass-through.

There is still one bug I haven't been able to solve in the time I had, but it is not a regression so I'm leaning towards glossing over it:

Consider this uri: `http://example.com/illegal-encoding-%86`:
'%86' is not a legal UTF-8 percent-encoding on its own, and but java's URI accepts it anyway. The result of this (along with the "withHost" bug that is addressed in this PR) is that the parsed request actually holds an illegal UTF-8 string...(!)

My fix here "moves" the bug from the allowIllegalCharacters **off** flow to the allowIllegalCharacters **on** one - because the proposed change here is to **not** encode "legal" uri-encoding.
(The existing implementation of the lenient uri parser just encodes '%' as '%25').

So, either ignore this issue, or correctly handle UTF-8 percent encoding (or at least in a compatible way to java's URI).

Either way, as this PR introduces a logical change (parseUriLenient does not encode already uri-encoded parts), maybe it's a good idea to add this as an option to RawHttpOptions - but I'm not sure what is the contract there. WDYT?

**Comment by renatoathaydes** [comment]
> '%86' is not a legal UTF-8 percent-encoding on its own, but java's URI accepts it anyway. 

That's because the [relevant RFC](https://tools.ietf.org/html/rfc3986#section-2.1) does not say that this is not legal! Neither does it say this is UTF-8, by the way, it's just a binary Octet, which usually is translated to text using US-ASCII in the context of URIs.

> Either way, as this PR introduces a logical change (parseUriLenient does not encode already uri-encoded parts), maybe it's a good idea to add this as an option to RawHttpOptions - but I'm not sure what is the contract there. WDYT?

I explained why I think this PR is not fixing an actual bug in the bug issue you've created: #15 .

Therefore, I cannot accept this pull request as the premise it's based on was flawed.

I am very sorry you spent time on this problem, but I hope you accept my arguments.

**Comment by idanga** [comment]
Thank you for the time reviewing this.
Firstly, don't be sorry at all - I'm using this excellent library to replay recorded raw-http traffic, and I needed the changes for my own use, so no time wasted on my part.
As you know, the web is the wild west with regards to adherence to standards, and many urls have mixed encoded and unencoded characters (especially REST apis).

Now, regarding the RFC you mentioned - see section https://tools.ietf.org/html/rfc3986#section-2.5 of that RFC:

...When a new URI scheme defines a component that represents textual
data consisting of characters from the Universal Character Set [UCS],
the data should first be encoded as octets according to the UTF-8
character encoding [STD63]; then **only those octets that do not
correspond to characters in the unreserved set should be percent-
encoded**.  For example, **the character A would be represented as "A",
the character LATIN CAPITAL LETTER A WITH GRAVE would be represented
as "%C3%80"**, and the character KATAKANA LETTER A would be represented
as "%E3%82%A2".

I believe this is a recommendation, not a must.
Anyway, as this is very much a corner case, I don't think it's even worth considering here.

However, I do think that the fix to withHost and toString or RequestLine should be merged. I'll open a new PR with those changes solely.

**Comment by renatoathaydes** [comment]
> I believe this is a recommendation, not a must.

This part of the RFC is speculative... notice how it starts with _When a new URI scheme defines..._. 

A few sentences above, it explains that _For most systems, an unreserved character appearing within a URI component is interpreted as representing the data octet corresponding to that character's encoding in US-ASCII._

In any case, I'll leave the difficult interpretation of these characters to Java, as that's used by millions of developers and it seems to be working fine :)

> However, I do think that the fix to withHost and toString or RequestLine should be merged

I agree there's a bug there, but I disagree with the fix. I don't have a fix yet myself, but I am looking into it.... will keep you posted.

**Pull request closed without merging**
